#include "Led64.h"

// Define some colors
#define BLACK   0x000000
#define WHITE   0xFFFFFF
#define RED     0xFF0000
#define GREEN   0x00FF00
#define BLUE    0x0000FF
#define YELLOW  0xFFFF00
#define ORANGE  0xFFA500

const uint32_t SMILEY_BITMAP[64] = {
    BLACK,  BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, BLACK,  BLACK,
    BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
    YELLOW, YELLOW, BLACK,  YELLOW, YELLOW, BLACK,  YELLOW, YELLOW,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    YELLOW, BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, BLACK,  YELLOW,
    YELLOW, YELLOW, BLACK,  BLACK,  BLACK,  BLACK,  YELLOW, YELLOW,
    BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
    BLACK,  BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, BLACK,  BLACK
};

const uint32_t BATTERY_BITMAP[64] = {
    BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,
    BLACK,  BLACK,  WHITE,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK,
    BLACK,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  WHITE,  BLACK,
    BLACK,  WHITE,  GREEN,  GREEN,  GREEN,  GREEN,  WHITE,  BLACK,
    BLACK,  WHITE,  GREEN,  GREEN,  GREEN,  GREEN,  WHITE,  BLACK,
    BLACK,  WHITE,  GREEN,  GREEN,  GREEN,  GREEN,  WHITE,  BLACK,
    BLACK,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  WHITE,  BLACK,
    BLACK,  BLACK,  WHITE,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK
};

const uint32_t SUN_BITMAP[64] = {
    BLACK,  BLACK,  BLACK,  YELLOW, YELLOW, BLACK,  BLACK,  BLACK,
    BLACK,  YELLOW, BLACK,  YELLOW, YELLOW, BLACK,  YELLOW, BLACK,
    BLACK,  BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, BLACK,  BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    BLACK,  BLACK,  YELLOW, YELLOW, YELLOW, YELLOW, BLACK,  BLACK,
    BLACK,  YELLOW, BLACK,  YELLOW, YELLOW, BLACK,  YELLOW, BLACK,
    BLACK,  BLACK,  BLACK,  YELLOW, YELLOW, BLACK,  BLACK,  BLACK
};

const uint32_t MOON_BITMAP[64] = {
    BLACK,  BLACK,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK,
    BLACK,  BLACK,  WHITE,  WHITE,  WHITE,  BLACK,  BLACK,  BLACK
};

const uint32_t WARNING_BITMAP[64] = {
    BLACK,  BLACK,  BLACK,  YELLOW, YELLOW, BLACK,  BLACK,  BLACK,
    BLACK,  BLACK,  YELLOW, RED,    RED,    YELLOW, BLACK,  BLACK,
    BLACK,  YELLOW, YELLOW, RED,    RED,    YELLOW, YELLOW, BLACK,
    BLACK,  YELLOW, YELLOW, RED,    RED,    YELLOW, YELLOW, BLACK,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
    YELLOW, YELLOW, YELLOW, BLACK,  BLACK,  YELLOW, YELLOW, YELLOW,
    YELLOW, YELLOW, YELLOW, RED,    RED,    YELLOW, YELLOW, YELLOW,
    YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
};

const uint32_t WIFI_LOST_BITMAP[64] = {
    RED,    BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  RED,
    BLACK,  RED,    BLACK,  WHITE,  WHITE,  BLACK,  RED,    BLACK,
    BLACK,  BLACK,  RED,    WHITE,  WHITE,  RED,    BLACK,  BLACK,
    BLACK,  WHITE,  WHITE,  RED,    RED,    WHITE,  WHITE,  BLACK,
    BLACK,  WHITE,  WHITE,  RED,    RED,    WHITE,  WHITE,  BLACK,
    BLACK,  BLACK,  RED,    WHITE,  WHITE,  RED,    BLACK,  BLACK,
    BLACK,  RED,    BLACK,  WHITE,  WHITE,  BLACK,  RED,    BLACK,
    RED,    BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  BLACK,  RED
};

Led64::Led64(int16_t pin) : _pixels(64, pin, NEO_GRB + NEO_KHZ800) {
}

void Led64::begin() {
    _pixels.begin();
    _pixels.clear();
    _pixels.show();
}

void Led64::smiley() {
    _displayBitmap(SMILEY_BITMAP);
}

void Led64::battery() {
    _displayBitmap(BATTERY_BITMAP);
}

void Led64::sun() {
    _displayBitmap(SUN_BITMAP);
}

void Led64::moon() {
    _displayBitmap(MOON_BITMAP);
}

void Led64::warning() {
    _displayBitmap(WARNING_BITMAP);
}

void Led64::wifiLost() {
    _displayBitmap(WIFI_LOST_BITMAP);
}

void Led64::clear() {
    _pixels.clear();
    _pixels.show();
}

void Led64::_displayBitmap(const uint32_t bitmap[64]) {
    for(int i = 0; i < 64; i++) {
        _pixels.setPixelColor(i, bitmap[i]);
    }
    _pixels.show();
}
